version: "3.8"

services:
  postgres:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bookkicker
      - POSTGRES_PASSWORD=bookkicker
    ports:
      - "5432"
  bot:
    build: .
    environment:
      - DB_HOST=postgres
      - PYTHONUNBUFFERED=1

volumes:
  postgres_data:
